version: '3.9'

services:
  database:
    image: postgres:latest
    container_name: htmx_todo_list_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=htmx_todo_list_db
    profiles: [dev, prod]
